### ISSUE TITLE
I got Attribute error when running the code. Anyone can help me with it? Many thx.

### ISSUE THREAD

**Issue by Avalon7** [svishwa/crowdcount-mcnn#35]
Traceback (most recent call last):
  File "train.py", line 106, in <module>
    density_map = net(im_data, gt_data)
  File "/usr/local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/Users/yinweicheng/Desktop/job/summer-project/crowdcount-mcnn/src/crowd_count.py", line 17, in forward
    im_data = network.np_to_variable(im_data, is_cuda=False, is_training=self.training)
AttributeError: module 'network' has no attribute 'np_to_variable'

**Comment by Avalon7** [comment]
Solved, shouldn't use python3.
